### PR TITLE
Add support for https://github.com/Telerik-Verified-Plugins/WKWebView

### PR DESCRIPTION
**Pull request by mbrio**
This commit adds support for native transitions to work with the WKWebView cordova plugin.

### CODE REVIEW

**Comment by EddyVerbruggen** [comment]
Hi, thanks a bunch!

This will mean you need to compile with iOS 8 SDK, but that should not affect anyone these days.

Gimme some time to evaluate your PR.

**Comment by mbrio** [comment]
Hi Eddy,

I need to make one change, so sorry about this, unfortunately there's a bug in WKWebView that doesn't allow you to take a screenshot of it using the `UIGraphicsGetImageFromCurrentImageContext` call. I didn't notice it because I was dumb and didn't test it on a device, only in the emulator (where the bug doesn't exist).

Will send a new pull request shortly.

**Comment by mbrio** [comment]
I've updated my pull to fix the screenshot bug that exists in iOS 8 where WKWebView will not allow an image to be created of it using the `renderInContext` method. This exists on device only, not in emulator.

**Comment by EddyVerbruggen** [comment]
Hi @mbrio it's part of the 0.2.13 version I just released. Thanks for your efforts!

**Comment by mbrio** [comment]
Great to hear, and no problem, this plugin helped me greatly with one of the projects I'm working on.

**Pull request merged**
