### PR TITLE
Update NativePageTransitions.m

### PR DESCRIPTION
**Pull request by Emadello**
Setting transitioning view to:
self.viewController.view
to include tabbar and navbar if exists

### CODE REVIEW

**Comment by EddyVerbruggen** [comment]
Thanks! Do you mean a native navbar/tabbar? If so, did you use a plugin or a custom storyboard (I'd like to reproduce this).

**Comment by Emadello** [comment]
Yes, actually not only native tabbar and navbar, but any other native component added to the view.

Please check my profile, I added 2 plugins for native navbar and tabbar for ios.

I tested it with them and they work perfectly.

**Comment by EddyVerbruggen** [comment]
Tested, confirmed it works, thanks! :+1: 

Btw, sweet plugins, are you considering Android support?

**Comment by Emadello** [comment]
Thanks!

I will make android version soon :)

Also your plugin is amazing! I love it, it's a great addition to Cordova, keep it up 👍

**Comment by EddyVerbruggen** [comment]
Thank you, I'm interested in yours as well, so adding a watch :)

**Comment by Emadello** [comment]
My pleasure sir :)

**Comment by EddyVerbruggen** [comment]
Ouch, this caused some regression after all; the transition may now kick in after the page has updated to the new state. Details in #114, I'll try to fix it in a way that this will not break.

**Comment by EddyVerbruggen** [comment]
I had to roll this back in v 0.6.2. I wasn't really able to break the transitions on iOS with the navbar plugin enabled. As long as I set `fixedPixelsTop` to 0.

**Pull request merged**
